coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 75%
        threshold: 5%
        base: auto

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true

ignore:
  # Исключения для Codecov (аналогично JaCoCo)
  - "**/*Application.java"
  - "**/config/**"
  - "**/dto/**"
  - "**/entity/**"
  - "**/autoconfigure/**"
  - "**/*$*"
  - "**/target/**"
  - "**/generated-sources/**"
