# 📊 Codecov Configuration - Настройка анализа покрытия кода
#
# Оптимизирована для предотвращения дублирования проверок между PR и push событиями
# Разделяет обработку PR валидации и обновления метрик основной ветки

# Общие настройки покрытия
coverage:
  precision: 2
  round: down
  range: "70...100"

  # Статусы проверки покрытия
  status:
    # Проверка покрытия всего проекта
    project:
      default:
        target: 80%                    # Минимальное покрытие проекта
        threshold: 1%                  # Допустимое снижение
        base: auto                     # Автоматическое определение базы
        if_ci_failed: error           # Статус при падении CI
        only_pulls: false             # Проверять и PR и push

      # Дополнительные правила для PR
      pr-validation:
        target: 80%
        threshold: 2%                  # Более мягкий порог для PR
        base: auto
        if_ci_failed: error
        only_pulls: true              # Только для PR

    # Проверка покрытия изменений (патч)
    patch:
      default:
        target: 75%                   # Минимальное покрытие новых изменений
        threshold: 5%                 # Допустимое снижение для патча
        base: auto
        only_pulls: true              # Только для PR

# Настройки комментариев в PR
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false            # Комментировать даже без изменений
  require_base: false              # Не требовать базовый коммит
  require_head: true               # Требовать head коммит
  after_n_builds: 1                # Комментировать после первой сборки

# GitHub интеграция
github_checks:
  annotations: true                 # Добавлять аннотации к коду

# Предотвращение дублирования между PR и push
flag_management:
  default_rules:
    carryforward: true              # Переносить флаги между билдами

  individual_flags:
    # Флаг для валидации PR
    - name: pr-validation
      paths:
        - "src/"
      carryforward: false

    # Флаг для основной ветки
    - name: main-branch
      paths:
        - "src/"
      carryforward: true

    # Флаг для unit тестов
    - name: unittests
      paths:
        - "src/"
      carryforward: true

# Игнорируемые файлы и директории
ignore:
  # Spring Boot специфичные исключения
  - "**/*Application.java"          # Главные классы приложения
  - "**/config/**"                  # Конфигурационные классы
  - "**/dto/**"                     # Data Transfer Objects
  - "**/entity/**"                  # JPA сущности
  - "**/autoconfigure/**"           # Автоконфигурация Spring Boot

  # Lombok и generated код
  - "**/*$*"                        # Внутренние классы от Lombok
  - "**/generated-sources/**"       # Генерируемые источники

  # Build артефакты
  - "**/target/**"                  # Maven build директория
  - "**/build/**"                   # Gradle build директория

  # Тестовые ресурсы
  - "**/src/test/resources/**"      # Тестовые ресурсы

# Парсинг отчетов
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# Настройки уведомлений
notify:
  # Уведомления в Slack (опционально)
  slack:
    default:
      only_pulls: true
      message: "Coverage report for {{owner}}/{{repo}}"

# Проверка валидности YAML конфигурации
codecov:
  require_ci_to_pass: yes           # Требовать успешный CI
  notify:
    after_n_builds: 1               # Уведомлять после первой сборки
    wait_for_ci: yes                # Ждать завершения CI
